### ISSUE TITLE
White screen while booting

### ISSUE THREAD

**Issue by Koro142** [vvctre/vvctre#16]
Hello! Glad to see you´re all still working on this beauty. I was a bit scared when the other page just went and vanished.

I have a lil question. When I boot the exe, it appears to be loading, but I always end up with just a white screen. If I try to click on it, the application freezes. I have a 4.0 OpenGL, so I don't think that's the issue. Grated, I only downloaded what was in Releases, so I don't know if I should've downloaded something else, nor if I have to put the script folder or the source folder in the same folder as the exe. I have a previous version, the vvctre51.1.0 that worked alright in my PC, but I can see this looks like something different.

Anyways, I thought to ask, just in case anyone can help me with that. Either way, keep up the good work!

**Comment by vvanelslande** [comment]
https://vvctre.github.io
